name: Smoke Tests

on:
  pull_request:
  push:
    branches:
      - master
      - 001-act-as-the

jobs:
  smoke-suite:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run smoke encoding tests
        run: pytest tests/smoke/test_file_encoding.py
